//auth actions types
export const AUTH_USER_SIGNUP_PENDING = 'AUTH_USER_SIGNUP_PENDING';
export const AUTH_USER_SIGNUP_ERROR = 'AUTH_USER_SIGNUP_ERROR';
export const AUTH_USER_SIGNUP_SUCCESS = 'AUTH_USER_SIGNUP_SUCCESS';
export const AUTH_USER_SIGNUP_CLEAR = 'AUTH_USER_SIGNUP_CLEAR';

export const AUTH_USER_SIGNIN_PENDING = 'AUTH_USER_SIGNIN_PENDING';
export const AUTH_USER_SIGNIN_ERROR = 'AUTH_USER_SIGNIN_ERROR';
export const AUTH_USER_SIGNIN_SUCCESS = 'AUTH_USER_SIGNIN_SUCCESS';
export const AUTH_USER_SIGNIN_CLEAR = 'AUTH_USER_SIGNIN_CLEAR';

//boards actions
export const BOARDS_PENDING = 'BOARDS_PENDING'
export const BOARDS_ERROR = 'BOARDS_ERROR'
export const BOARDS_CLEAR = 'BOARDS_CLEAR'
export const BOARDS_GETALL_SUCCESS = 'BOARDS_GETALL_SUCCESS'

export const BOARDS_BOARD_PENDING = 'BOARDS_BOARD_PENDING'
export const BOARDS_BOARD_ERROR = 'BOARDS_BOARD_ERROR'
export const BOARDS_BOARD_CLEAR = 'BOARDS_BOARD_CLEAR'

export const BOARDS_BOARD_GET_SUCCESS = 'BOARDS_BOARD_GET_SUCCESS'
export const BOARDS_BOARD_DELETE_SUCCESS = 'BOARDS_BOARD_DELETE_SUCCESS'
export const BOARDS_BOARD_ADD_SUCCESS = 'BOARDS_BOARD_ADD_SUCCESS'
export const BOARDS_BOARD_EDIT_SUCCESS = 'BOARDS_BOARD_EDIT_SUCCESS'