//auth actions types
export const AUTH_USER_SIGNUP_PENDING = 'AUTH_USER_SIGNUP_PENDING';
export const AUTH_USER_SIGNUP_ERROR = 'AUTH_USER_SIGNUP_ERROR';
export const AUTH_USER_SIGNUP_SUCCESS = 'AUTH_USER_SIGNUP_SUCCESS';
export const AUTH_USER_SIGNUP_CLEAR = 'AUTH_USER_SIGNUP_CLEAR';
export const AUTH_USER_SIGNIN_PENDING = 'AUTH_USER_SIGNIN_PENDING';
export const AUTH_USER_SIGNIN_ERROR = 'AUTH_USER_SIGNIN_ERROR';
export const AUTH_USER_SIGNIN_SUCCESS = 'AUTH_USER_SIGNIN_SUCCESS';
export const AUTH_USER_SIGNIN_CLEAR = 'AUTH_USER_SIGNIN_CLEAR';