//auth actions types
export const AUTH_USER_SIGNUP_PENDING = 'AUTH_USER_SIGNUP_PENDING';
export const AUTH_USER_SIGNUP_ERROR = 'AUTH_USER_SIGNUP_ERROR';
export const AUTH_USER_SIGNUP_SUCCESS = 'AUTH_USER_SIGNUP_SUCCESS';
export const AUTH_USER_SIGNUP_CLEAR = 'AUTH_USER_SIGNUP_CLEAR';

export const AUTH_USER_SIGNIN_PENDING = 'AUTH_USER_SIGNIN_PENDING';
export const AUTH_USER_SIGNIN_ERROR = 'AUTH_USER_SIGNIN_ERROR';
export const AUTH_USER_SIGNIN_SUCCESS = 'AUTH_USER_SIGNIN_SUCCESS';
export const AUTH_USER_SIGNIN_CLEAR = 'AUTH_USER_SIGNIN_CLEAR';

//boards actions types
export const BOARDS_PENDING = 'BOARDS_PENDING'
export const BOARDS_ERROR = 'BOARDS_ERROR'
export const BOARDS_CLEAR = 'BOARDS_CLEAR'
export const BOARDS_GETALL_SUCCESS = 'BOARDS_GETALL_SUCCESS'

export const BOARDS_BOARD_PENDING = 'BOARDS_BOARD_PENDING'
export const BOARDS_BOARD_ERROR = 'BOARDS_BOARD_ERROR'
export const BOARDS_BOARD_CLEAR = 'BOARDS_BOARD_CLEAR'

export const BOARDS_BOARD_GET_SUCCESS = 'BOARDS_BOARD_GET_SUCCESS'
export const BOARDS_BOARD_DELETE_SUCCESS = 'BOARDS_BOARD_DELETE_SUCCESS'
export const BOARDS_BOARD_ADD_SUCCESS = 'BOARDS_BOARD_ADD_SUCCESS'
export const BOARDS_BOARD_EDIT_SUCCESS = 'BOARDS_BOARD_EDIT_SUCCESS'

//notes actions types
export const NOTES_PENDING = 'NOTES_PENDING'
export const NOTES_ERROR = 'NOTES_ERROR'
export const NOTES_CLEAR = 'NOTES_CLEAR'
export const NOTES_GETALL_SUCCESS = 'NOTES_GETALL_SUCCESS'
export const NOTES_GETBYBOARD_SUCCESS = 'NOTES_GETBYBOARD_SUCCESS'

export const NOTES_NOTE_PENDING = 'NOTES_NOTE_PENDING'
export const NOTES_NOTE_ERROR = 'NOTES_NOTE_ERROR'
export const NOTES_NOTE_CLEAR = 'NOTES_NOTE_CLEAR'

export const NOTES_NOTE_GET_SUCCESS = 'NOTES_NOTE_GET_SUCCESS'
export const NOTES_NOTE_DELETE_SUCCESS = 'NOTES_NOTE_DELETE_SUCCESS'
export const NOTES_NOTE_ADD_SUCCESS = 'NOTES_NOTE_ADD_SUCCESS'
export const NOTES_NOTE_EDIT_SUCCESS = 'NOTES_NOTE_EDIT_SUCCESS'
